application: kevin-cs253
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:                                                                      
- name: jinja2                                                                  
  version: latest

handlers:
- url: /static
  static_dir: static

- url: .*
  script: main.app
  
- url: /blog/(\d+)
  script: ...  
